import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { TranslationsProvider } from "@/components/translation-context";
import { DebateProvider } from "@/contexts/debate-context";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ModeToggle } from "@/components/theme-toggler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} h-screen`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <DebateProvider>
              <TranslationsProvider>
                <header className="w-full flex justify-between items-center p-4 border-b">
                  <h1 className="text-xl font-bold">iThink</h1>
                  <div className="flex gap-x-5">
                    <Link href={"/debate"}>
                      <Button>Start Debate</Button>
                    </Link>
                    <ModeToggle />
                  </div>
                </header>
                {children}</TranslationsProvider>
            </DebateProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
